import { AgentSkill } from "../../harness/index.ts";

export const CreateStudyArtifactsSkill = AgentSkill.make({
  name: "create-study-artifacts",
  description: "Create and manage study artifacts: markdown notes, quizzes, tests, interactive diagrams, submissions, and graded attempts.",
  content: [
    "# Create study artifacts",
    "",
    "Use this skill when the user asks you to create study notes, quizzes, tests, diagrams (esquemas, mapas conceptuales, flujos), or practice submissions.",
    "",
    "Artifacts are persisted study objects:",
    "- `note`: title plus markdown content. Notes are not submitted or graded.",
    "- `quiz`: title plus auto-gradable multiple-choice / true-false questions.",
    "- `test`: title plus questions. Tests may include multiple-choice, true-false, and short-answer questions.",
    "- `diagram`: title plus interactive node/edge graph. Use for esquemas, mapas conceptuales, diagramas de flujo, mind maps. Nodes represent concepts; edges show relationships. Rendered as an interactive canvas the user can pan/zoom and click.",
    "",
    "Available CLI commands:",
    "- `artifacts list [note|quiz|test|diagram]`: list saved artifacts.",
    "- `artifacts show <artifactId>`: show an artifact JSON.",
    "- `artifacts create '<json>'`: create a note, quiz, test, or diagram from CreateArtifactInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts submit '<json>'`: submit answers for a quiz or test from SubmitAttemptInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts attempts [artifactId]`: list attempts.",
    "- `artifacts grade <attemptId>`: grade and persist a submitted attempt.",
    "",
    "CreateArtifactInput examples:",
    "- `artifacts create '{\"kind\":\"note\",\"title\":\"Derivatives summary\",\"markdown\":\"# Derivatives\\n...\"}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Basics quiz\",\"questions\":[{\"type\":\"true-false\",\"id\":\"q1\",\"prompt\":\"2+2=4\",\"correctAnswer\":true,\"explanation\":\"Basic arithmetic.\"}]}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Concept quiz\",\"questions\":[{\"type\":\"multiple-choice\",\"id\":\"q1\",\"prompt\":\"Which option is qualitative?\",\"options\":[{\"id\":\"qualitative\",\"text\":\"Qualitative\"},{\"id\":\"quantitative\",\"text\":\"Quantitative\"}],\"correctOptionId\":\"qualitative\",\"explanation\":\"Qualitative data describes qualities.\"}]}'`",
    "- `artifacts create '{\"kind\":\"diagram\",\"title\":\"Fotosíntesis\",\"layout\":\"flowchart\",\"nodes\":[{\"id\":\"n1\",\"label\":\"Luz solar\",\"concept\":\"Fuente de energía inicial\"},{\"id\":\"n2\",\"label\":\"Clorofila\",\"concept\":\"Pigmento que absorbe la luz\"},{\"id\":\"n3\",\"label\":\"Glucosa\",\"concept\":\"Producto energético final\"}],\"edges\":[{\"id\":\"e1\",\"source\":\"n1\",\"target\":\"n2\",\"label\":\"absorbida por\"},{\"id\":\"e2\",\"source\":\"n2\",\"target\":\"n3\",\"label\":\"produce\"}]}'`",
    "",
    "Multiple-choice question rules:",
    "- `options` must be objects, not strings: `{\"id\":\"a\",\"text\":\"Option text\"}`.",
    "- `correctOptionId` must exactly match one option `id`.",
    "",
    "Diagram rules (STRICT — the frontend renders a hierarchical DAG with dagre):",
    "- `layout` must be one of: `flowchart` (top-down process, TD), `mindmap` (left-right from root, LR), `concept-map` (top-down category tree, TD).",
    "- STRUCTURE MUST BE A HIERARCHY / DAG:",
    "  * Exactly ONE root node (a node with no incoming edges). It represents the main topic.",
    "  * Every non-root node MUST have at least one incoming edge from a parent higher in the hierarchy.",
    "  * NO CYCLES. NO back-edges. NO orphan nodes.",
    "  * Aim for 3 tiers: root → categories → leaves (details).",
    "- EDGE SEMANTICS:",
    "  * Every edge is directed `source` → `target` where source is the parent (higher in hierarchy) and target is the child.",
    "  * Every edge MUST have a `label` that is a short action verb or preposition in active voice describing the relationship: \"define\", \"incluye\", \"se compone de\", \"produce\", \"hereda de\", \"contiene\", \"usa\", \"gestiona\", \"consiste en\", \"conecta con\".",
    "  * Read the edge aloud as \"[source] [label] [target]\" — it must be a grammatical sentence in Spanish.",
    "- LABELS: node labels are short (1-4 words). Use `concept` for the 1-2 sentence explanation shown on click.",
    "- IDS: stable strings — nodes `n1`, `n2`, ...; edges `e1`, `e2`, ...",
    "- SIZE: 5-15 nodes, 4-20 edges. If the topic is bigger, split into multiple diagrams (create them separately).",
    "",
    "SubmitAttemptInput example:",
    "- `artifacts submit '{\"artifactKind\":\"quiz\",\"artifactId\":\"<id>\",\"answers\":[{\"questionType\":\"true-false\",\"questionId\":\"q1\",\"answer\":true}]}'`",
    "",
    "Workflow:",
    "1. For artifacts based on uploaded materials, inspect the uploaded material first.",
    "2. Create a compact artifact that directly matches the user's request.",
    "3. Use stable question / node / edge ids like `q1`, `n1`, `e1`.",
    "4. For quizzes, use ONLY true-false and multiple-choice (grading is deterministic — instant self-check).",
    "4b. For tests, use MOSTLY short-answer questions (at least 70% of the questions). Optionally include 1-2 multiple-choice or true-false. Short-answer questions are what make a test more than a quiz.",
    "4c. Short-answer grading is a case-insensitive string match against `expectedAnswer`. So `expectedAnswer` MUST be a short canonical form (1-3 words, no articles, no filler) — e.g. `\"encapsulación\"`, not `\"la encapsulación oculta el estado interno\"`. Write the question prompt so the natural answer IS that canonical form.",
    "5. When a user submits answers, save the attempt and then grade it.",
    "",
    "Routing hints (Spanish):",
    "- \"esquema\", \"diagrama\", \"mapa conceptual\", \"mapa mental\", \"flujo\", \"grafo\", \"relaciones\" → create a `diagram` artifact. Do NOT reply with ASCII art or markdown outlines.",
    "- \"resumen\", \"apuntes\", \"nota\" → create a `note` artifact.",
    "- \"test\", \"examen\", \"prueba\" → create a `test` artifact.",
    "- \"quiz\", \"cuestionario\", \"preguntas rápidas\" → create a `quiz` artifact.",
    "- After creating a visual artifact, respond in chat with ONE short sentence pointing to it. Never repeat the diagram/quiz/test content inline."
  ].join("\n")
});
